services:
  - type: static
    name: nt-crud-frontend
    env: static
    plan: free
    autoDeploy: true
    buildCommand: ""
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /health
        destination: /index.html
