services:
  - type: web
    name: nt-crud-app
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    # Build backend service using its own Dockerfile and context
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    dockerCommand: "node server.js"
