services:
  - type: web
    name: nt-crud-frontend
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 80
    # Build frontend only using its Dockerfile and context
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
